models:  
  qwen3:
    model: ai/qwen3

  gpt-oss:
    model: ai/gpt-oss

services:
  mcp-gateway:
    image: docker/mcp-gateway:latest
    use_api_socket: true
    command:
      - --transport=sse
      - --servers=time,github
      - --tools=time:get_current_time
      - --tools=github:create_issue
    secrets:
      - mcp_secret

  app:
    image: tadashinemoto567/compose-ai-agent-demo-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://docker:pass@db:5432/chatstore
      - MCP_GATEWAY_URL=http://mcp-gateway:8811/sse
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    models:
      - qwen3
      - gpt-oss
    depends_on:
      - mcp-gateway
      - db
      - initialize-db-schema

  db:
    image: postgres:17.6-alpine
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=chatstore
    volumes:
      - chat_store:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d chatstore"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  initialize-db-schema:
    image: tadashinemoto567/compose-ai-agent-demo-initialize-db-schema
    build:
      context: .
      dockerfile: Dockerfile.initialize-db-schema
    environment:
      - DATABASE_URL=postgresql://docker:pass@db:5432/chatstore
    depends_on:
      db:
        condition: service_healthy

volumes:
  chat_store:

secrets:
  mcp_secret:
    file: ./.mcp.env
